In [23]:
import numpy as np

array1 = np.array([1,2,3,4])

lista1 = [1,2,3,4]

print(f"Array: {array1}")
print(f"Lista: {lista1}")

print(array1[2])

# multiplicera alla tal med 2
array2 = array1*2
print(array2)

lista2 = lista1*2
print(lista2)

kvadrater = array1**2
print(kvadrater)

Array: [1 2 3 4]
Lista: [1, 2, 3, 4]
3
[2 4 6 8]
[1, 2, 3, 4, 1, 2, 3, 4]
[ 1  4  9 16]


In [48]:
import numpy as np
# Uppgift 1
# A:
array = np.arange(1,11)
print(f"A:\n{array}")

# B:
array1 = np.arange(-11,11)
print(f"B:\n{array1}")


A:
[ 1  2  3  4  5  6  7  8  9 10]
B:
[-11 -10  -9  -8  -7  -6  -5  -4  -3  -2  -1   0   1   2   3   4   5   6
   7   8   9  10]


In [53]:
import numpy as np
# Uppgift 2

array = np.arange(10,110,10)
print(array)

tio = array*10
print(tio)

[ 10  20  30  40  50  60  70  80  90 100]
[ 100  200  300  400  500  600  700  800  900 1000]


In [58]:
import matplotlib.pyplot as plt

array = ([0, , 10])

plt.plot(array)
plt.xlabel("X")
plt.ylabel("Y")
plt.show()

NameError: name 'x' is not defined